"use client";
import { useState } from "react";
import jsPDF from "jspdf";

const ashtangaPrimary = [
  { phase: "Opening", poses: ["Surya Namaskara A (5x)", "Surya Namaskara B (5x)"] },
  { phase: "Standing", poses: ["Padangusthasana", "Padahastasana", "Utthita Trikonasana", "Parivrtta Trikonasana", "Utthita Parsvakonasana", "Parivrtta Parsvakonasana", "Prasarita Padottanasana A–D", "Parsvottanasana", "Utthita Hasta Padangusthasana", "Ardha Baddha Padmottanasana", "Utkatasana", "Virabhadrasana A & B"] },
  { phase: "Primary Series (Seated)", poses: ["Dandasana", "Paschimottanasana A–C", "Purvottanasana", "Ardha Baddha Padma Paschimottanasana", "Triang Mukhaikapada Paschimottanasana", "Janu Sirsasana A–C", "Marichyasana A–D", "Navasana (5x)", "Bhujapidasana", "Kurmasana", "Supta Kurmasana", "Garbha Pindasana", "Kukkutasana", "Baddha Konasana A & B", "Upavistha Konasana", "Supta Konasana", "Supta Padangusthasana", "Ubhaya Padangusthasana", "Urdhva Mukha Paschimottanasana", "Setu Bandhasana"] },
  { phase: "Finishing", poses: ["Urdhva Dhanurasana (3x)", "Paschimottanasana", "Salamba Sarvangasana", "Halasana", "Karnapidasana", "Urdhva Padmasana", "Pindasana", "Matsyasana", "Uttana Padasana", "Sirsasana", "Baddha Padmasana", "Yoga Mudra", "Padmasana", "Tolasana"] },
  { phase: "Closing", poses: ["Savasana (minimum 5 min)"] },
];

const rocketIII = [
  { phase: "Opening", poses: ["Surya Namaskara A (3x)", "Surya Namaskara B (3x)"] },
  { phase: "Standing", poses: ["Padangusthasana", "Padahastasana", "Trikonasana", "Parivrtta Trikonasana", "Parsvakonasana", "Parivrtta Parsvakonasana", "Prasarita Padottanasana A–D", "Parsvottanasana", "Utthita Hasta Padangusthasana", "Utkatasana", "Virabhadrasana A & B"] },
  { phase: "Rocket I (Primary Seated)", poses: ["Dandasana", "Paschimottanasana", "Purvottanasana", "Janu Sirsasana A", "Marichyasana A", "Marichyasana C", "Navasana (3x)", "Bhujapidasana", "Kurmasana", "Supta Kurmasana", "Garbha Pindasana", "Kukkutasana", "Baddha Konasana", "Upavistha Konasana", "Supta Konasana"] },
  { phase: "Rocket II (Intermediate Seated)", poses: ["Pashasana", "Krounchasana", "Shalabhasana A & B", "Bhekasana", "Dhanurasana", "Parsva Dhanurasana", "Ustrasana", "Laghu Vajrasana", "Kapotasana", "Supta Vajrasana", "Bakasana", "Bharadvajasana", "Ardha Matsyendrasana", "Eka Pada Sirsasana", "Yoganidrasana", "Tittibhasana"] },
  { phase: "Finishing", poses: ["Urdhva Dhanurasana (3x)", "Paschimottanasana", "Salamba Sarvangasana", "Halasana", "Karnapidasana", "Matsyasana", "Sirsasana", "Balasana"] },
  { phase: "Closing", poses: ["Savasana (minimum 5 min)"] },
];

function downloadAshtangaPDF() {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const margin = 20;
  let y = 20;
  doc.setFont("helvetica", "bold"); doc.setFontSize(20);
  doc.text("Ashtanga Primary Series", margin, y); y += 6;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(120);
  doc.text("Traditional sequence as taught by Sri K. Pattabhi Jois", margin, y); y += 10;
  doc.setDrawColor(200); doc.line(margin, y, 210 - margin, y); y += 8;
  ashtangaPrimary.forEach((section) => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(80, 60, 180);
    doc.text(section.phase.toUpperCase(), margin, y); y += 6;
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(40);
    section.poses.forEach((pose, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`${i + 1}. ${pose}`, margin + 4, y); y += 5.5;
    });
    y += 4;
  });
  doc.setFontSize(8); doc.setTextColor(160);
  doc.text("Generated by Vinyasaurus Flex", margin, 290);
  doc.save("ashtanga-primary-series.pdf");
}

function downloadRocketPDF() {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const margin = 20;
  let y = 20;
  doc.setFont("helvetica", "bold"); doc.setFontSize(20);
  doc.text("Rocket III", margin, y); y += 6;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(120);
  doc.text("Developed by Larry Schultz — \"Because it gets you there faster.\"", margin, y); y += 10;
  doc.setDrawColor(200); doc.line(margin, y, 210 - margin, y); y += 8;
  rocketIII.forEach((section) => {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(80, 60, 180);
    doc.text(section.phase.toUpperCase(), margin, y); y += 6;
    doc.setFont("helvetica", "normal"); doc.setFontSize(10); doc.setTextColor(40);
    section.poses.forEach((pose, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(`${i + 1}. ${pose}`, margin + 4, y); y += 5.5;
    });
    y += 4;
  });
  doc.setFontSize(8); doc.setTextColor(160);
  doc.text("Generated by Vinyasaurus Flex", margin, 290);
  doc.save("rocket-III.pdf");
}

export default function Home() {
  const [peak, setPeak] = useState("");
  const [duration, setDuration] = useState("60");
  const [style, setStyle] = useState("Vinyasa");
  const [sequence, setSequence] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function generateSequence() {
    if (!peak) { setError("Please enter a peak pose."); return; }
    setError("");
    setLoading(true);
    setSequence(null);
    try {
      const res = await fetch("/api/generate-sequence", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ peak, duration, style }),
      });
      const data = await res.json();
      let clean = data.sequence.replace(/```json|```/g, "").trim();
      const firstBrace = clean.indexOf("{");
      const lastBrace = clean.lastIndexOf("}");
      clean = clean.slice(firstBrace, lastBrace + 1);
      const parsed = JSON.parse(clean);
      try {
        const yogaRes = await fetch("https://yoga-api-nzy4.onrender.com/v1/poses");
        const yogaPoses = await yogaRes.json();
        parsed.phases.forEach((phase: any) => {
          phase.poses.forEach((pose: any) => {
            const poseName = pose.name?.toLowerCase().trim();
            const match = yogaPoses.find((p: any) => {
              const apiName = p.english_name?.toLowerCase().trim();
              return (
                apiName === poseName ||
                (apiName && poseName && apiName.length > 6 && poseName.includes(apiName)) ||
                (apiName && poseName && poseName.length > 6 && apiName.includes(poseName))
              );
            });
            if (match) pose.image = match.url_png;
          });
        });
      } catch {
        console.log("Could not load pose images");
      }
      setSequence(parsed);
    } catch (e) {
      console.error(e);
      setError("Something went wrong. Please try again.");
    }
    setLoading(false);
  }

  const phaseColors: Record<string, string> = {
    warm: "#EF9F27",
    build: "#1D9E75",
    peak: "#7F77DD",
    cool: "#378ADD",
    close: "#888780",
  };

  const sectionColors = ["#7F77DD", "#1D9E75", "#EF9F27", "#378ADD", "#888780"];

  return (
    <div className="min-h-screen font-sans">

      {/* Header */}
      <header className="sticky top-0 bg-white z-50 shadow-sm px-4 sm:px-10 py-4 flex justify-between items-center">
        <h2 className="text-base sm:text-xl font-semibold m-0">Vinyasaurus Flex 🦕</h2>
        <nav className="flex gap-4 sm:gap-6">
          <a href="/" className="no-underline text-black text-sm sm:text-base">Home</a>
          <a href="/about" className="no-underline text-black text-sm sm:text-base">About</a>
        </nav>
      </header>

      {/* Hero */}
      <section
        className="relative h-screen flex flex-col justify-center items-center text-white text-center px-6"
        style={{ backgroundImage: "url('/yoga.jpg')", backgroundSize: "cover", backgroundPosition: "center" }}
      >
        <div className="absolute inset-0 bg-black/40" />
        <div className="relative z-10 max-w-2xl">
          <h1 className="text-4xl sm:text-5xl font-bold mb-4">Vinyasaurus Flex</h1>
          <p className="text-base sm:text-lg mb-8 leading-relaxed">
            A yoga sequencing app for teachers. Choose a peak pose, class duration,
            and style — and get a full sequence instantly.
          </p>
          <a href="#builder" className="bg-white text-black px-6 py-3 rounded-md font-medium hover:bg-gray-100 transition">
            Get Started
          </a>
        </div>
      </section>

      {/* Sequence Builder */}
      <section id="builder" className="max-w-3xl mx-auto px-4 sm:px-6 py-16 sm:py-20">
        <h2 className="text-2xl font-semibold mb-2">Build your sequence</h2>
        <p className="text-gray-500 mb-8">Enter your class details and get a suggested flow.</p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
          <div className="flex flex-col gap-1">
            <label className="text-xs uppercase tracking-wide text-gray-500 font-medium">Peak Pose</label>
            <input
              type="text"
              placeholder="e.g. Crow Pose"
              value={peak}
              onChange={e => setPeak(e.target.value)}
              onKeyDown={e => e.key === "Enter" && generateSequence()}
              className="border border-gray-200 rounded-lg px-3 h-10 text-sm focus:outline-none focus:ring-2 focus:ring-purple-200"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs uppercase tracking-wide text-gray-500 font-medium">Duration</label>
            <select
              value={duration}
              onChange={e => setDuration(e.target.value)}
              className="border border-gray-200 rounded-lg px-3 h-10 text-sm focus:outline-none focus:ring-2 focus:ring-purple-200"
            >
              <option value="30">30 minutes</option>
              <option value="45">45 minutes</option>
              <option value="60">60 minutes</option>
              <option value="75">75 minutes</option>
              <option value="90">90 minutes</option>
            </select>
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs uppercase tracking-wide text-gray-500 font-medium">Style</label>
            <select
              value={style}
              onChange={e => setStyle(e.target.value)}
              className="border border-gray-200 rounded-lg px-3 h-10 text-sm focus:outline-none focus:ring-2 focus:ring-purple-200"
            >
              <option>Vinyasa</option>
              <option>Hatha</option>
              <option>Yin</option>
              <option>Restorative</option>
              <option>Power Yoga</option>
              <option>Ashtanga</option>
              <option>Kundalini</option>
              <option>Iyengar</option>
            </select>
          </div>
        </div>

        <button
          onClick={generateSequence}
          disabled={loading}
          className="w-full h-11 rounded-lg border border-gray-200 text-sm font-medium hover:bg-gray-50 transition disabled:opacity-50 flex items-center justify-center gap-2"
        >
          {loading ? "Building your sequence..." : "✨ Generate sequence"}
        </button>

        {error && <p className="text-red-500 text-sm mt-3">{error}</p>}

        {sequence && (
          <div className="mt-12">
            <div className="grid grid-cols-3 gap-2 sm:gap-3 mb-8">
              {[["Peak Pose", peak], ["Duration", `${duration} min`], ["Style", style]].map(([label, value]) => (
                <div key={label} className="bg-gray-50 rounded-lg p-2 sm:p-3">
                  <p className="text-xs uppercase tracking-wide text-gray-400 mb-1">{label}</p>
                  <p className="text-xs sm:text-sm font-medium">{value}</p>
                </div>
              ))}
            </div>
            {sequence.summary && (
              <p className="text-sm text-gray-500 italic mb-8">{sequence.summary}</p>
            )}
            {sequence.phases?.map((phase: any) => (
              <div key={phase.name} className="mb-8">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-2 h-2 rounded-full" style={{ background: phaseColors[phase.type] || "#888" }} />
                  <h3 className="text-xs uppercase tracking-widest text-gray-500 font-medium">{phase.name}</h3>
                  <span className="ml-auto text-xs text-gray-400">{phase.duration_minutes} min</span>
                </div>
                <div className="flex flex-col gap-2">
                  {phase.poses?.map((pose: any, i: number) => (
                    <div key={i} className="border border-gray-100 rounded-xl p-3 flex gap-3 items-center">
                      <span className="text-xs text-gray-300 w-5 shrink-0">{i + 1}</span>
                      {pose.image && (
                        <img src={pose.image} alt={pose.name} className="w-12 h-12 sm:w-14 sm:h-14 object-contain shrink-0" />
                      )}
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium">
                          {pose.name}
                          {pose.is_peak && (
                            <span className="ml-2 text-xs bg-purple-100 text-purple-600 px-2 py-0.5 rounded-full">★ peak</span>
                          )}
                        </p>
                        {pose.sanskrit && <p className="text-xs text-gray-400 mt-0.5">{pose.sanskrit}</p>}
                        {pose.note && <p className="text-xs text-gray-400 italic mt-1">{pose.note}</p>}
                      </div>
                      <span className="text-xs text-gray-400 whitespace-nowrap">{pose.duration}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* Ashtanga Primary Series */}
      <section className="max-w-3xl mx-auto px-4 sm:px-6 pb-16 sm:pb-24">
        <div className="border border-gray-100 rounded-2xl p-5 sm:p-8">
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-2">
            <div>
              <h2 className="text-2xl font-semibold mb-1">Ashtanga Primary Series</h2>
              <p className="text-gray-500 text-sm">
                Rejecting Modernity and Embracing Tradition? The traditional set sequence as taught by Sri K. Pattabhi Jois — also known as <em>Yoga Chikitsa</em> (Yoga Therapy).
                The word "Ashtanga" comes from the Sanskrit <em>Ashta</em> (eight) and <em>Anga</em> (limbs), referring to the Eight Limbs of Yoga
                described in the Yoga Sutras of Patanjali.
              </p>
            </div>
            <button
              onClick={downloadAshtangaPDF}
              className="w-full sm:w-auto shrink-0 flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition"
            >
              ⬇ Download PDF
            </button>
          </div>
          <div className="mt-8 flex flex-col gap-8">
            {ashtangaPrimary.map((section, si) => (
              <div key={section.phase}>
                <div className="flex items-center gap-2 mb-3">
                  <div className="w-2 h-2 rounded-full" style={{ background: sectionColors[si] }} />
                  <h3 className="text-xs uppercase tracking-widest text-gray-500 font-medium">{section.phase}</h3>
                </div>
                <div className="flex flex-col gap-1.5">
                  {section.poses.map((pose, i) => (
                    <div key={i} className="flex items-center gap-3 border border-gray-100 rounded-xl px-4 py-2.5">
                      <span className="text-xs text-gray-300 w-5 shrink-0">{i + 1}</span>
                      <span className="text-sm">{pose}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Rocket III */}
      <section className="max-w-3xl mx-auto px-4 sm:px-6 pb-16 sm:pb-24">
        <div className="border border-gray-100 rounded-2xl p-5 sm:p-8">
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-2">
            <div>
              <h2 className="text-2xl font-semibold mb-1">Rocket III</h2>
              <p className="text-gray-500 text-sm">
                Developed by Larry Schultz — a dynamic combination of Rocket I and Rocket II.
                Known for its playful, accessible approach to Ashtanga with the motto: <em>"It lets you do it now."</em>
              </p>
            </div>
            <button
              onClick={downloadRocketPDF}
              className="w-full sm:w-auto shrink-0 flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-700 text-white text-sm font-medium px-4 py-2 rounded-lg transition"
            >
              ⬇ Download PDF
            </button>
          </div>
          <div className="mt-8 flex flex-col gap-8">
            {rocketIII.map((section, si) => (
              <div key={section.phase}>
                <div className="flex items-center gap-2 mb-3">
                  <div className="w-2 h-2 rounded-full" style={{ background: sectionColors[si % sectionColors.length] }} />
                  <h3 className="text-xs uppercase tracking-widest text-gray-500 font-medium">{section.phase}</h3>
                </div>
                <div className="flex flex-col gap-1.5">
                  {section.poses.map((pose, i) => (
                    <div key={i} className="flex items-center gap-3 border border-gray-100 rounded-xl px-4 py-2.5">
                      <span className="text-xs text-gray-300 w-5 shrink-0">{i + 1}</span>
                      <span className="text-sm">{pose}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      
     {/* Footer */}
      <footer className="border-t border-gray-100 py-10 text-center px-6">
        
          <a href="https://www.buymeacoffee.com/lizdraper"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 bg-yellow-400 hover:bg-yellow-500 text-black px-4 py-2 rounded-lg text-sm font-medium transition"
        >
          ☕ Buy me a coffee
        </a>
        <p className="text-xs text-gray-400 mt-4">© 2026 Vinyasaurus Flex · <a href="/privacy" className="underline">Privacy Policy</a></p>
      </footer>

    </div>
  );
}